language: node_js
node_js:
- '6.3'
before_script:
- npm install -g jest typescript@2.1
dd:
  secure: K7PikcxxeKBQUm1FDGdZI40cEZIF5aqqLGOoCxt3mcouf3vcRG6dkwxpZ6sl76/DVE03l7lEpI0pccnE2ixec1nURgeV9uNPNhsoPyu1o00b6yGBx2kQs9YbjE4h7UYAfDwbvOSMZ0kp4P+D67axbYqVuKEuXppggI9k+EmDr5XyuuIW53ETCuToXUA/ElIK9QZ7eIn7+lAffH4RtAk7vgmpanyLUQCauGrKOaHGvXe6RNvcFFQXZtbKQ/h7pE16GMVuXHkOFVKPPfI+VEDA5F8qAnUMbMMT8tsMfFQVj3nVULQyQRrQAMDPfnqSXcNWs8rKJ1nHub9TSB04Yxg/nstJRX++qirijLNZvPyAaz91C12W+evaogKmetReXv7BQiHYZS4ROiyLOtftn98vWi/rDgVor5wzX9pzXNyDeixhNjtwYJndG8RDgqEqDTotO6+d/TE79Z5WQvObttnYrfTy6fsvHVw7mXtpPbpNkAlL6ZKBagWlwX243j9qIevX+UBfDTHz+nqcignXoTcFCwpLEZ9R9//oD69N9Uw4pxR02LtU7x/I89ntG8Hr/FLwhbwkX9mbCfztmtYvzGDq1ocQcwEOY41XvFk6LR78WMb0uKFrOC7ywJGuXkeIUEmTlPhJRVunft8QBz3w6xVrdThhIucKZlgYDoWaLrdwNK8=
deploy:
  provider: npm
  email: jonathan.glanz@gmail.com
  api_key:
    secure: Ap7/R/j3JmendAovJtsDQeP6o1LUKkMKrIIaXOaTBjyNtLS2KNowBKaGx/7yhZVh3RqHGiFNOG7OABYnN565yFmVIuaFNHI27DgnXu2dOR6scuQ53fjF+aIqY/NVhpm55PCIYIYF6VEHKA63Qsi0ou33VHalwfws5ViEbS3lWUWar2CjBaFIxLQUpsFqIaBJ65gg342mFOPiC1JFcI0reorCGH/nVVSZTsIEIXmhoYGCxcjOGs3ynAwvV+acJnB5LDfoHcnSD4c7lEiHMZ2Q8pSTFFujxqI4C4vE0T0aOWRLs+kwcridwpiGmqaR1xK2hMBvGe7irov/lOyxZ35HTTy6x1vyd49b5qWviNAfjZJ8/dgpkHa7TVfm/bAIsK2Bk22C46poGHpVxJWKd3AWinwYN8AYv1JvwPFYbvbLXzKH4OZVFiaQy88EIJp1P3uLV1k5j5sPVGrnS9pVP+k0NpoGZAJYainDFLsz3WrSxV9g+bF9GHt3+iAoHNR6O8GHA89LTEcnpP6Kih+bDDNko1vWVsS5W6ZccZ8rsAHwSfWVGNq4XU213CHrz20TVGb0UMdwuywJEzpi1gp0kvjz2LxV/S2BdjIIS/AMvj4fv/hdgM3/EJ8uM5uhc8wuLXbDMe/862LNIEr33Fv7JKnDIqyHQq7FDPYO5BJjYppMUdI=
  on:
    branch: master
    tags: true
#    repo: densebrain/typelogger

